pokemonChanges = {
  "Bulbasaur": ["Overgrow", "Overgrow", "Overgrow", "Poison Point", "3", "5"],
  "Caterpie": ["Shield Dust", "Shield Dust", "Shield Dust", "Shield Dust", "0", "5"],
  "Voltorb": ["Soundproof", "Static", "Static", "Soundproof", "0", "0"],
  "Electrode": ["Soundproof", "Static", "Static", "Soundproof", "0", "0"],
  "Exeggcute": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "5", "5"],
  "Hitmonlee": ["Limber", "Limber", "Limber", "Limber", "0", "0"],
  "Hitmonchan": ["Keen Eye", "Battle Armor", "Keen Eye", "Battle Armor", "0", "0"],
  "Lickitung": ["Own Tempo", "Own Tempo", "Oblivious", "Oblivious", "0", "0"],
  "Koffing": ["Levitate", "Levitate", "Levitate", "Levitate", "0", "0"],
  "Metapod": ["Shed Skin", "Shed Skin", "Shed Skin", "Shed Skin", "0", "5"],
  "Weezing": ["Levitate", "Levitate", "Levitate", "Levitate", "0", "0"],
  "Rhyhorn": ["Lightningrod", "Rock Head", "Rock Head", "Lightningrod", "5", "5"],
  "Rhydon": ["Lightningrod", "Rock Head", "Rock Head", "Lightningrod", "5", "5"],
  "Chansey": ["Natural Cure", "Natural Cure", "Serene Grace", "Serene Grace", "4", "4"],
  "Tangela": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "0", "0"],
  "Kangaskhan": ["Early Bird", "Early Bird", "Early Bird", "Early Bird", "0", "0"],
  "Seadra": ["Poison Point", "Swift Swim", "Poison Point", "Swift Swim", "0", "0"],
  "Goldeen": ["Swift Swim", "Swift Swim", "Water Veil", "Water Veil", "0", "0"],
  "Seaking": ["Swift Swim", "Swift Swim", "Water Veil", "Water Veil", "0", "0"],
  "Butterfree": ["Compoundeyes", "Shield Dust", "Compoundeyes", "Shield Dust", "0", "5"],
  "Staryu": ["Illuminate", "Natural Cure", "Natural Cure", "Illuminate", "5", "5"],
  "Starmie": ["Illuminate", "Natural Cure", "Natural Cure", "Illuminate", "5", "5"],
  "Mr. Mime": ["Soundproof", "Soundproof", "Soundproof", "Soundproof", "0", "0"],
  "Scyther": ["Swarm", "Swarm", "Swarm", "Swarm", "0", "0"],
  "Electabuzz": ["Static", "Static", "Static", "Static", "0", "0"],
  "Pinsir": ["Hyper Cutter", "Hyper Cutter", "Hyper Cutter", "Hyper Cutter", "5", "5"],
  "Tauros": ["Intimidate", "Intimidate", "Intimidate", "Intimidate", "5", "5"],
  "Gyarados": ["Intimidate", "Swift Swim", "Intimidate", "Swift Swim", "5", "5"],
  "Lapras": ["Water Absorb", "Shell Armor", "Shell Armor", "Water Absorb", "5", "5"],
  "Ditto": ["Limber", "Limber", "Limber", "Limber", "0", "0"],
  "Eevee": ["Run Away", "Run Away", "Run Away", "Run Away", "0", "0"],
  "Vaporeon": ["Water Absorb", "Water Absorb", "Water Absorb", "Water Absorb", "0", "0"],
  "Jolteon": ["Volt Absorb", "Volt Absorb", "Volt Absorb", "Volt Absorb", "0", "0"],
  "Flareon": ["Flash Fire", "Drought", "Flash Fire", "Flash Fire", "0", "0"],
  "Omanyte": ["Swift Swim", "Shell Armor", "Shell Armor", "Swift Swim", "0", "0"],
  "Omastar": ["Swift Swim", "Shell Armor", "Shell Armor", "Swift Swim", "0", "0"],
  "Kabuto": ["Swift Swim", "Swift Swim", "Battle Armor", "Battle Armor", "0", "0"],
  "Kabutops": ["Swift Swim", "Swift Swim", "Battle Armor", "Battle Armor", "0", "0"],
  "Aerodactyl": ["Rock Head", "Rock Head", "Pressure", "Pressure", "5", "5"],
  "Snorlax": ["Immunity", "Thick Fat", "Thick Fat", "Immunity", "5", "5"],
  "Articuno": ["Pressure", "Pressure", "Pressure", "Pressure", "5", "5"],
  "Zapdos": ["Pressure", "Pressure", "Pressure", "Pressure", "5", "5"],
  "Moltres": ["Pressure", "Pressure", "Pressure", "Pressure", "5", "5"],
  "Dratini": ["Shed Skin", "Shed Skin", "Shed Skin", "Shed Skin", "5", "5"],
  "Dragonair": ["Shed Skin", "Shed Skin", "Shed Skin", "Shed Skin", "5", "5"],
  "Beedrill": ["Swarm", "Swarm", "Swarm", "Swarm", "0", "0"],
  "Mewtwo": ["Pressure", "Pressure", "Pressure", "Pressure", "5", "5"],
  "Meganium": ["Overgrow", "Overgrow", "Overgrow", "Overgrow", "3", "3"],
  "Typhlosion": ["Blaze", "Blaze", "Blaze", "Blaze", "3", "3"],
  "Totodile": ["Torrent", "Torrent", "Torrent", "Torrent", "3", "3"],
  "Croconaw": ["Torrent", "Torrent", "Torrent", "Torrent", "3", "3"],
  "Pidgey": ["Keen Eye", "Keen Eye", "Keen Eye", "Keen Eye", "3", "3"],
  "Feraligatr": ["Torrent", "Torrent", "Torrent", "Torrent", "3", "3"],
  "Sentret": ["Run Away", "Guts", "Keen Eye", "Guts", "0", "0"],
  "Furret": ["Run Away", "Guts", "Keen Eye", "Guts", "0", "0"],
  "Hoothoot": ["Insomnia", "Insomnia", "Keen Eye", "Keen Eye", "0", "0"],
  "Noctowl": ["Insomnia", "Insomnia", "Keen Eye", "Compoundeyes", "0", "0"],
  "Ledyba": ["Swarm", "Early Bird", "Early Bird", "Swarm", "4", "4"],
  "Ledian": ["Swarm", "Early Bird", "Early Bird", "Swarm", "4", "4"],
  "Spinarak": ["Swarm", "Intimidate", "Insomnia", "Intimidate", "4", "4"],
  "Ariados": ["Swarm", "Intimidate", "Insomnia", "Intimidate", "4", "4"],
  "Pidgeotto": ["Keen Eye", "Early Bird", "Keen Eye", "Early Bird", "3", "3"],
  "Lanturn": ["Volt Absorb", "Volt Absorb", "Illuminate", "Illuminate", "5", "5"],
  "Igglybuff": ["Cute Charm", "Cute Charm", "Cute Charm", "Soundproof", "4", "4"],
  "Togepi": ["Hustle", "Serene Grace", "Serene Grace", "Hustle", "4", "4"],
  "Togetic": ["Hustle", "Serene Grace", "Serene Grace", "Hustle", "4", "4"],
  "Natu": ["Synchronize", "Synchronize", "Early Bird", "Early Bird", "0", "0"],
  "Xatu": ["Synchronize", "Synchronize", "Early Bird", "Early Bird", "0", "0"],
  "Mareep": ["Static", "Static", "Static", "Static", "3", "3"],
  "Pidgeot": ["Keen Eye", "Early Bird", "Keen Eye", "Early Bird", "3", "3"],
  "Flaaffy": ["Static", "Static", "Static", "Static", "3", "3"],
  "Ampharos": ["Static", "Static", "Static", "Static", "3", "3"],
  "Bellossom": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Flash Fire", "3", "3"],
  "Marill": ["Thick Fat", "Huge Power", "Huge Power", "Huge Power", "4", "4"],
  "Azumarill": ["Thick Fat", "Huge Power", "Huge Power", "Huge Power", "4", "4"],
  "Sudowoodo": ["Sturdy", "Sturdy", "Rock Head", "Rock Head", "0", "0"],
  "Politoed": ["Water Absorb", "Water Absorb", "Damp", "Thick Fat", "3", "3"],
  "Hoppip": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "3", "3"],
  "Skiploom": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "3", "3"],
  "Jumpluff": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "3", "3"],
  "Rattata": ["Run Away", "Guts", "Guts", "Hustle", "0", "0"],
  "Aipom": ["Run Away", "Limber", "Pickup", "Limber", "4", "4"],
  "Sunkern": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "3", "3"],
  "Sunflora": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "3", "3"],
  "Yanma": ["Speed Boost", "Compoundeyes", "Compoundeyes", "Compoundeyes", "0", "0"],
  "Wooper": ["Damp", "Water Absorb", "Water Absorb", "Swift Swim", "0", "0"],
  "Quagsire": ["Damp", "Water Absorb", "Water Absorb", "Swift Swim", "0", "0"],
  "Espeon": ["Synchronize", "Synchronize", "Synchronize", "Synchronize", "0", "0"],
  "Umbreon": ["Synchronize", "Synchronize", "Synchronize", "Synchronize", "0", "0"],
  "Murkrow": ["Insomnia", "Insomnia", "Insomnia", "Insomnia", "3", "3"],
  "Slowking": ["Oblivious", "Oblivious", "Own Tempo", "Own Tempo", "0", "0"],
  "Ivysaur": ["Overgrow", "Overgrow", "Overgrow", "Poison Point", "3", "5"],
  "Raticate": ["Run Away", "Guts", "Guts", "Hustle", "0", "0"],
  "Misdreavus": ["Levitate", "Levitate", "Levitate", "Levitate", "4", "4"],
  "Unown": ["Levitate", "Levitate", "Levitate", "Levitate", "0", "0"],
  "Girafarig": ["Inner Focus", "Inner Focus", "Early Bird", "Early Bird", "0", "0"],
  "Pineco": ["Sturdy", "Shell Armor", "Sturdy", "Shell Armor", "0", "0"],
  "Forretress": ["Sturdy", "Shell Armor", "Sturdy", "Shell Armor", "0", "0"],
  "Dunsparce": ["Serene Grace", "Serene Grace", "Run Away", "Serene Grace", "0", "0"],
  "Snubbull": ["Intimidate", "Intimidate", "Run Away", "Intimidate", "4", "4"],
  "Spearow": ["Keen Eye", "Keen Eye", "Keen Eye", "Keen Eye", "0", "0"],
  "Granbull": ["Intimidate", "Intimidate", "Intimidate", "Intimidate", "4", "4"],
  "Qwilfish": ["Poison Point", "Intimidate", "Swift Swim", "Intimidate", "0", "0"],
  "Shuckle": ["Sturdy", "Shell Armor", "Sturdy", "Shell Armor", "3", "3"],
  "Sneasel": ["Inner Focus", "Inner Focus", "Keen Eye", "Inner Focus", "3", "3"],
  "Teddiursa": ["Pickup", "Keen Eye", "Pickup", "Pickup", "0", "0"],
  "Ursaring": ["Guts", "Guts", "Guts", "Intimidate", "0", "0"],
  "Slugma": ["Magma Armor", "Water Absorb", "Flame Body", "Water Absorb", "0", "0"],
  "Magcargo": ["Magma Armor", "Water Absorb", "Flame Body", "Water Absorb", "0", "0"],
  "Fearow": ["Keen Eye", "Sand Veil", "Keen Eye", "Sand Veil", "0", "0"],
  "Swinub": ["Oblivious", "Thick Fat", "Oblivious", "Thick Fat", "5", "5"],
  "Piloswine": ["Oblivious", "Thick Fat", "Oblivious", "Thick Fat", "5", "5"],
  "Corsola": ["Hustle", "Natural Cure", "Natural Cure", "Hustle", "4", "4"],
  "Remoraid": ["Hustle", "Swift Swim", "Hustle", "Swift Swim", "0", "0"],
  "Octillery": ["Suction Cups", "Swift Swim", "Suction Cups", "Swift Swim", "0", "0"],
  "Delibird": ["Vital Spirit", "Vital Spirit", "Hustle", "Hustle", "4", "4"],
  "Mantine": ["Swift Swim", "Swift Swim", "Water Absorb", "Water Absorb", "5", "5"],
  "Skarmory": ["Keen Eye", "Keen Eye", "Sturdy", "Sturdy", "5", "5"],
  "Houndour": ["Early Bird", "Intimidate", "Flash Fire", "Flash Fire", "5", "5"],
  "Houndoom": ["Early Bird", "Intimidate", "Flash Fire", "Flash Fire", "5", "5"],
  "Ekans": ["Intimidate", "Intimidate", "Shed Skin", "Intimidate", "0", "0"],
  "Donphan": ["Sturdy", "Rock Head", "Sturdy", "Rock Head", "0", "0"],
  "Porygon2": ["Trace", "Trace", "Trace", "Trace", "0", "0"],
  "Stantler": ["Intimidate", "Intimidate", "Intimidate", "Intimidate", "5", "5"],
  "Smeargle": ["Own Tempo", "Own Tempo", "Own Tempo", "Own Tempo", "4", "4"],
  "Tyrogue": ["Guts", "Guts", "Guts", "Guts", "0", "0"],
  "Hitmontop": ["Intimidate", "Intimidate", "Intimidate", "Intimidate", "0", "0"],
  "Smoochum": ["Oblivious", "Oblivious", "Oblivious", "Oblivious", "0", "0"],
  "Elekid": ["Static", "Static", "Static", "Static", "0", "0"],
  "Arbok": ["Intimidate", "Intimidate", "Shed Skin", "Intimidate", "0", "0"],
  "Magby": ["Flame Body", "Flame Body", "Flame Body", "Flame Body", "0", "0"],
  "Miltank": ["Thick Fat", "Thick Fat", "Thick Fat", "Thick Fat", "5", "5"],
  "Blissey": ["Natural Cure", "Oblivious", "Serene Grace", "Oblivious", "4", "4"],
  "Raikou": ["Pressure", "Inner Focus", "Pressure", "Inner Focus", "5", "5"],
  "Entei": ["Pressure", "Inner Focus", "Pressure", "Inner Focus", "5", "5"],
  "Suicune": ["Pressure", "Inner Focus", "Pressure", "Inner Focus", "5", "5"],
  "Pupitar": ["Shed Skin", "Shed Skin", "Shed Skin", "Shed Skin", "5", "5"],
  "Tyranitar": ["Sand Stream", "Intimidate", "Sand Stream", "Intimidate", "5", "5"],
  "Lugia": ["Pressure", "Pressure", "Pressure", "Pressure", "5", "5"],
  "Ho-Oh": ["Pressure", "Pressure", "Pressure", "Pressure", "5", "5"],
  "Celebi": ["Natural Cure", "Natural Cure", "Natural Cure", "Natural Cure", "3", "3"],
  "?": ["Ursapluff", "No Ability", "Chlorophyll", "No Ability", "Chlorophyll", "0", "0"],
  "Sandshrew": ["Sand Veil", "Sand Veil", "Sand Veil", "Sand Veil", "0", "0"],
  "Sandslash": ["Sand Veil", "Poison Point", "Sand Veil", "Rough Skin", "0", "0"],
  "Poochyena": ["Meltan", "Run Away", "Magnet Pull", "Run Away", "Magnet Pull", "0", "5"],
  "Mightyena": ["Melmetal", "Intimidate", "Hyper Cutter", "Intimidate", "Hyper Cutter", "0", "5"],
  "Zigzagoon": ["Venusaurm", "Pickup", "Thick Fat", "Pickup", "Thick Fat", "0", "0"],
  "Linoone": ["Charizardx", "Pickup", "Flash Fire", "Pickup", "Flash Fire", "0", "0"],
  "Nidoran-F": ["Poison Point", "Poison Point", "Poison Point", "Poison Point", "3", "3"],
  "Wurmple": ["Geodude-Alola", "Shield Dust", "Magnet Pull", "Shield Dust", "Sturdy", "0", "3"],
  "Silcoon": ["Graveler-Alola", "Shed Skin", "Magnet Pull", "Shed Skin", "Sturdy", "0", "3"],
  "Beautifly": ["Golem-Alola", "Swarm", "Magnet Pull", "Swarm", "Sturdy", "0", "3"],
  "Cascoon": ["Vulpix-Alola", "Shed Skin", "Flash Fire", "Shed Skin", "Flash Fire", "0", "0"],
  "Dustox": ["Ninetalesa", "Shield Dust", "Flash Fire", "Shield Dust", "Flash Fire", "0", "0"],
  "Lotad": ["Ambipom", "Swift Swim", "Limber", "Rain Dish", "Limber", "3", "4"],
  "Lombre": ["Mismagius", "Swift Swim", "Levitate", "Rain Dish", "Levitate", "3", "4"],
  "Ludicolo": ["Honchkrow", "Swift Swim", "Insomnia", "Rain Dish", "Insomnia", "3", "3"],
  "Seedot": ["Magnezone", "Chlorophyll", "Magnet Pull", "Early Bird", "Sturdy", "3", "0"],
  "Nuzleaf": ["Lickilicky", "Chlorophyll", "Serene Grace", "Early Bird", "Limber", "3", "0"],
  "Venusaur": ["Overgrow", "Overgrow", "Overgrow", "Poison Point", "3", "5"],
  "Nidorina": ["Poison Point", "Poison Point", "Poison Point", "Poison Point", "3", "3"],
  "Shiftry": ["Rhyperior", "Chlorophyll", "Rock Head", "Early Bird", "Lightningrod", "3", "5"],
  "Shroomish": ["Bonsly", "Effect Spore", "Sturdy", "Effect Spore", "Rock Head", "2", "0"],
  "Breloom": ["Mantyke", "Effect Spore", "Swift Swim", "Effect Spore", "Water Absorb", "2", "5"],
  "Spinda": ["Own Tempo", "Own Tempo", "Own Tempo", "Own Tempo", "4", "4"],
  "Wingull": ["Pikachu-F", "Keen Eye", "Static", "Keen Eye", "Static", "0", "0"],
  "Pelipper": ["Pikachu-S", "Keen Eye", "Static", "Keen Eye", "Static", "0", "0"],
  "Surskit": ["Mr. Mime-Galar", "Swift Swim", "Natural Cure", "Swift Swim", "Serene Grace", "0", "0"],
  "Masquerain": ["Mr. Rime", "Intimidate", "Inner Focus", "Intimidate", "Inner Focus", "0", "0"],
  "Wailmer": ["Slowpoke-Galar", "Water Veil", "Immunity", "Oblivious", "Serene Grace", "2", "0"],
  "Wailord": ["Slowbro-Galar", "Water Veil", "Speed Boost", "Oblivious", "Speed Boost", "2", "0"],
  "Skitty": ["Diglett-Alola", "Cute Charm", "Arena Trap", "Cute Charm", "Sand Veil", "4", "0"],
  "Delcatty": ["Dugtrio-Alola", "Cute Charm", "Arena Trap", "Cute Charm", "Magnet Pull", "4", "0"],
  "Kecleon": ["Weavile", "Color Change", "Pressure", "Color Change", "Pressure", "3", "3"],
  "Baltoy": ["Togekiss", "Levitate", "Serene Grace", "Levitate", "Hustle", "0", "4"],
  "Claydol": ["Yanmega", "Levitate", "Compoundeyes", "Levitate", "Compoundeyes", "0", "0"],
  "Nosepass": ["Gliscor", "Sturdy", "Hyper Cutter", "Magnet Pull", "Sand Veil", "0", "3"],
  "Torkoal": ["Screamtail", "White Smoke", "Trace", "White Smoke", "Trace", "0", "5"],
  "Sableye": ["Mamoswine", "Keen Eye", "Thick Fat", "Keen Eye", "Thick Fat", "3", "5"],
  "Barboach": ["Meowth-Alola", "Oblivious", "Pickup", "Oblivious", "Pickup", "0", "0"],
  "Whiscash": ["Persian-Alola", "Oblivious", "Intimidate", "Oblivious", "Intimidate", "0", "0"],
  "Luvdisc": ["Gallade", "Swift Swim", "Inner Focus", "Swift Swim", "Inner Focus", "4", "5"],
  "Corphish": ["Qwilfish-H", "Hyper Cutter", "Poison Point", "Shell Armor", "Swift Swim", "2", "0"],
  "Crawdaunt": ["Overqwil", "Hyper Cutter", "Poison Point", "Shell Armor", "Swift Swim", "2", "0"],
  "Nidorino": ["Poison Point", "Poison Point", "Poison Point", "Poison Point", "3", "3"],
  "Carvanha": ["Sneasel-H", "Rough Skin", "Inner Focus", "Rough Skin", "Inner Focus", "5", "3"],
  "Sharpedo": ["Sneasler", "Rough Skin", "Pressure", "Rough Skin", "Pressure", "5", "3"],
  "Flygon": ["Levitate", "Levitate", "Levitate", "Levitate", "3", "3"],
  "Electrike": ["Wiglett", "Static", "Swift Swim", "Lightningrod", "Sand Veil", "5", "5"],
  "Manectric": ["Wugtrio", "Static", "Swift Swim", "Lightningrod", "Sand Veil", "5", "5"],
  "Numel": ["Wyrdeer", "Oblivious", "Intimidate", "Oblivious", "Intimidate", "0", "5"],
  "Camerupt": ["Ursaluna", "Magma Armor", "Guts", "Magma Armor", "Thick Fat", "0", "0"],
  "Spheal": ["Rattata-Alola", "Thick Fat", "Guts", "Thick Fat", "Run Away", "3", "0"],
  "Sealeo": ["Raticate-Alola", "Thick Fat", "Guts", "Thick Fat", "Thick Fat", "3", "0"],
  "Walrein": ["Raichu-Alola", "Thick Fat", "Static", "Thick Fat", "Static", "3", "0"],
  "Cacnea": ["Grimer-Alola", "Sand Veil", "Sticky Hold", "Sand Veil", "Stench", "3", "0"],
  "Cacturne": ["Muk-Alola", "Sand Veil", "Sticky Hold", "Sand Veil", "Stench", "3", "0"],
  "Snorunt": ["Munchlax", "Inner Focus", "Thick Fat", "Inner Focus", "Pickup", "0", "5"],
  "Glalie": ["Kleavor", "Inner Focus", "Swarm", "Inner Focus", "Swarm", "0", "0"],
  "Lunatone": ["S. Shocks", "Levitate", "Static", "Levitate", "Static", "4", "5"],
  "Solrock": ["Blastoisem", "Levitate", "Shell Armor", "Levitate", "Shell Armor", "4", "4"],
  "Spoink": ["Sandshrewa", "Thick Fat", "Soundproof", "Own Tempo", "Soundproof", "4", "0"],
  "Grumpig": ["Sandslasha", "Thick Fat", "Soundproof", "Own Tempo", "Soundproof", "4", "0"],
  "Plusle": ["Leafeon", "Plus", "Chlorophyll", "Plus", "Chlorophyll", "0", "0"],
  "Minun": ["Glaceon", "Minus", "Clear Body", "Minus", "Clear Body", "0", "0"],
  "Mawile": ["Bronzong", "Hyper Cutter", "Levitate", "Intimidate", "Levitate", "4", "4"],
  "Meditite": ["Toedscool", "Pure Power", "Natural Cure", "Pure Power", "Water Absorb", "0", "5"],
  "Medicham": ["Toedscruel", "Pure Power", "Natural Cure", "Pure Power", "Water Absorb", "0", "5"],
  "Swablu": ["Growlitheh", "Natural Cure", "Intimidate", "Natural Cure", "Flash Fire", "1", "5"],
  "Altaria": ["Harcanine", "Natural Cure", "Intimidate", "Natural Cure", "Flash Fire", "1", "5"],
  "Wynaut": ["Shadow Tag", "Shadow Tag", "Shadow Tag", "Shadow Tag", "0", "0"],
  "Duskull": ["Voltorb-H", "Levitate", "Static", "Levitate", "Soundproof", "4", "0"],
  "Dusclops": ["Electrodeh", "Pressure", "Static", "Pressure", "Soundproof", "4", "0"],
  "Roselia": ["Annihilape", "Natural Cure", "Vital Spirit", "Poison Point", "Inner Focus", "3", "3"],
  "Slakoth": ["Corsola-Galar", "Truant", "Clear Body", "Truant", "Clear Body", "5", "4"],
  "Vigoroth": ["Cursola", "Vital Spirit", "Shadow Tag", "Vital Spirit", "Shadow Tag", "5", "4"],
  "Slaking": ["Dudunsparc", "Truant", "Serene Grace", "Truant", "Serene Grace", "5", "0"],
  "Gulpin": ["Porygon-Z", "Liquid Ooze", "Trace", "Sticky Hold", "Trace", "2", "0"],
  "Swalot": ["Weezing-Galar", "Liquid Ooze", "Levitate", "Sticky Hold", "Levitate", "2", "0"],
  "Tropius": ["Exeggutora", "Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "5", "5"],
  "Vulpix": ["Flash Fire", "Flash Fire", "Flash Fire", "Flash Fire", "0", "0"],
  "Whismur": ["Magmortar", "Soundproof", "Flame Body", "Soundproof", "Flame Body", "3", "0"],
  "Loudred": ["Electivire", "Soundproof", "Lightningrod", "Soundproof", "Lightningrod", "3", "3"],
  "Exploud": ["Tangrowth", "Soundproof", "Chlorophyll", "Soundproof", "Chlorophyll", "3", "0"],
  "Clamperl": ["Articuno-Galar", "Shell Armor", "Pressure", "Shell Armor", "Pressure", "1", "5"],
  "Huntail": ["Zapdos-Galar", "Swift Swim", "Pressure", "Swift Swim", "Pressure", "1", "5"],
  "Gorebyss": ["Moltres-Galar", "Swift Swim", "Pressure", "Swift Swim", "Pressure", "1", "5"],
  "Absol": ["Pressure", "Pressure", "Pressure", "Pressure", "3", "3"],
  "Shuppet": ["Marowak-Alola", "Insomnia", "Rock Head", "Insomnia", "Lightningrod", "4", "0"],
  "Banette": ["Meowth-Galar", "Insomnia", "Run Away", "Insomnia", "Run Away", "4", "0"],
  "Seviper": ["Perrserker", "Shed Skin", "Battle Armor", "Shed Skin", "Battle Armor", "2", "0"],
  "Ninetales": ["Flash Fire", "Flash Fire", "Flash Fire", "Flash Fire", "0", "0"],
  "Zangoose": ["Ponyta-Galar", "Immunity", "Flash Fire", "Immunity", "Run Away", "1", "0"],
  "Relicanth": ["Rapidash-Galar", "Swift Swim", "Flash Fire", "Rock Head", "White Smoke", "5", "0"],
  "Aron": ["Tauros-P", "Sturdy", "Intimidate", "Rock Head", "Intimidate", "5", "5"],
  "Lairon": ["Tauros-Pa", "Sturdy", "Swift Swim", "Rock Head", "Swift Swim", "5", "5"],
  "Aggron": ["Tauros-Pb", "Sturdy", "Flame Body", "Rock Head", "Flame Body", "5", "5"],
  "Castform": ["Mime Jr.", "Forecast", "Cute Charm", "Forecast", "Soundproof", "0", "0"],
  "Volbeat": ["Wooper-P", "Illuminate", "Water Absorb", "Swarm", "Poison Point", "1", "0"],
  "Illumise": ["Clodsire", "Oblivious", "Water Absorb", "Oblivious", "Poison Point", "2", "0"],
  "Lileep": ["Happiny", "Suction Cups", "Natural Cure", "Suction Cups", "Serene Grace", "1", "4"],
  "Cradily": ["Slowking-Galar", "Suction Cups", "Oblivious", "Suction Cups", "Own Tempo", "1", "0"],
  "Jigglypuff": ["Cute Charm", "Cute Charm", "Cute Charm", "Soundproof", "4", "4"],
  "Anorith": ["Farfetchdg", "Battle Armor", "Inner Focus", "Battle Armor", "Keen Eye", "1", "0"],
  "Armaldo": ["Sirfetch'D", "Battle Armor", "Inner Focus", "Battle Armor", "Keen Eye", "1", "0"],
  "Charmander": ["Blaze", "Blaze", "Blaze", "Flash Fire", "3", "5"],
  "Wigglytuff": ["Cute Charm", "Cute Charm", "Cute Charm", "Soundproof", "4", "4"],
  "Kyogre": ["Drizzle", "Drizzle", "Drizzle", "Drizzle", "5", "5"],
  "Groudon": ["Drought", "Drought", "Drought", "Drought", "5", "5"],
  "Rayquaza": ["Air Lock", "Air Lock", "Air Lock", "Air Lock", "5", "5"],
  "Zubat": ["Inner Focus", "Inner Focus", "Inner Focus", "Inner Focus", "0", "0"],
  "Chimecho": ["Farigiraf", "Levitate", "Inner Focus", "Levitate", "Intimidate", "4", "4"],
  "Oddish": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Serene Grace", "3", "3"],
  "Gloom": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Stench", "3", "3"],
  "Vileplume": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Serene Grace", "3", "3"],
  "Paras": ["Effect Spore", "Effect Spore", "Effect Spore", "Effect Spore", "0", "0"],
  "Parasect": ["Effect Spore", "Effect Spore", "Effect Spore", "Effect Spore", "0", "0"],
  "Venonat": ["Compoundeyes", "Compoundeyes", "Compoundeyes", "Compoundeyes", "0", "0"],
  "Venomoth": ["Shield Dust", "Shield Dust", "Shield Dust", "Shield Dust", "0", "0"],
  "Charmeleon": ["Blaze", "Blaze", "Blaze", "Flash Fire", "3", "5"],
  "Diglett": ["Sand Veil", "Arena Trap", "Arena Trap", "Sand Veil", "0", "0"],
  "Dugtrio": ["Sand Veil", "Arena Trap", "Arena Trap", "Sand Veil", "0", "0"],
  "Persian": ["Limber", "Compoundeyes", "Limber", "Compoundeyes", "0", "0"],
  "Psyduck": ["Damp", "Damp", "Cloud Nine", "Cloud Nine", "0", "0"],
  "Golduck": ["Damp", "Damp", "Cloud Nine", "Cloud Nine", "0", "0"],
  "Mankey": ["Vital Spirit", "Vital Spirit", "Vital Spirit", "Vital Spirit", "0", "0"],
  "Primeape": ["Vital Spirit", "Vital Spirit", "Vital Spirit", "Guts", "0", "0"],
  "Growlithe": ["Intimidate", "Intimidate", "Flash Fire", "Flash Fire", "5", "5"],
  "Charizard": ["Blaze", "Blaze", "Blaze", "Flash Fire", "3", "5"],
  "Poliwag": ["Water Absorb", "Water Absorb", "Damp", "Damp", "3", "3"],
  "Poliwhirl": ["Water Absorb", "Water Absorb", "Damp", "Damp", "3", "3"],
  "Poliwrath": ["Water Absorb", "Guts", "Damp", "Guts", "3", "3"],
  "Kadabra": ["Synchronize", "Synchronize", "Inner Focus", "Inner Focus", "3", "3"],
  "Alakazam": ["Synchronize", "Synchronize", "Inner Focus", "Inner Focus", "3", "3"],
  "Machop": ["Guts", "Guts", "Guts", "Guts", "3", "3"],
  "Bellsprout": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "3", "3"],
  "Squirtle": ["Torrent", "Torrent", "Torrent", "Shell Armor", "3", "5"],
  "Weepinbell": ["Chlorophyll", "Chlorophyll", "Chlorophyll", "Chlorophyll", "3", "3"],
  "Victreebel": ["Chlorophyll", "Intimidate", "Chlorophyll", "Intimidate", "3", "3"],
  "Ponyta": ["Run Away", "Flash Fire", "Flash Fire", "Run Away", "0", "0"],
  "Rapidash": ["Run Away", "Flash Fire", "Flash Fire", "Run Away", "0", "0"],
  "Slowpoke": ["Oblivious", "Oblivious", "Own Tempo", "Own Tempo", "0", "0"],
  "Wartortle": ["Torrent", "Torrent", "Torrent", "Shell Armor", "3", "5"],
  "Magnemite": ["Magnet Pull", "Magnet Pull", "Sturdy", "Sturdy", "0", "0"],
  "Farfetch'D": ["Keen Eye", "Pure Power", "Inner Focus", "Huge Power", "0", "0"],
  "Doduo": ["Run Away", "Early Bird", "Early Bird", "Run Away", "0", "0"],
  "Dodrio": ["Run Away", "Intimidate", "Early Bird", "Intimidate", "0", "0"],
  "Dewgong": ["Thick Fat", "Thick Fat", "Thick Fat", "Thick Fat", "0", "0"],
  "Grimer": ["Stench", "Sticky Hold", "Sticky Hold", "Stench", "0", "0"],
  "Muk": ["Stench", "Sticky Hold", "Sticky Hold", "Stench", "0", "0"],
  "Blastoise": ["Torrent", "Torrent", "Torrent", "Shell Armor", "3", "5"],
  "Shellder": ["Shell Armor", "Shell Armor", "Shell Armor", "Rain Dish", "5", "5"],
  "Cloyster": ["Shell Armor", "Shell Armor", "Shell Armor", "Rain Dish", "5", "5"],
  "Gengar": ["Levitate", "Levitate", "Levitate", "Levitate", "3", "3"],
  "Onix": ["Rock Head", "Rock Head", "Sturdy", "Sturdy", "0", "0"],
  "Drowzee": ["Insomnia", "Insomnia", "Insomnia", "Insomnia", "0", "0"],
  "Hypno": ["Insomnia", "Insomnia", "Insomnia", "Insomnia", "0", "0"],
  "Krabby": ["Hyper Cutter", "Shell Armor", "Shell Armor", "Hyper Cutter", "0", "0"],
  "Kingler": ["Hyper Cutter", "Shell Armor", "Shell Armor", "Hyper Cutter", "0", "0"]
};
